# Generated by Django 4.2.23 on 2025-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbacusExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('length_of_question', models.PositiveIntegerField()),
                ('number_of_questions', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField(help_text='Speed in seconds or as per requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
