# Generated by Django 4.2.23 on 2025-12-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyQuestion',
            fields=[
                ('serial', models.CharField(db_column='Serial', max_length=255, primary_key=True, serialize=False)),
                ('a', models.CharField(blank=True, db_column='A', max_length=255)),
                ('b', models.CharField(blank=True, db_column='B', max_length=255)),
                ('c', models.CharField(blank=True, db_column='C', max_length=255)),
                ('d', models.CharField(blank=True, db_column='D', max_length=255)),
                ('e', models.CharField(blank=True, db_column='E', max_length=255)),
                ('f', models.CharField(blank=True, db_column='F', max_length=255)),
                ('g', models.CharField(blank=True, db_column='G', max_length=255)),
                ('h', models.CharField(blank=True, db_column='H', max_length=255)),
                ('i', models.CharField(blank=True, db_column='I', max_length=255)),
                ('j', models.CharField(blank=True, db_column='J', max_length=255)),
                ('k', models.CharField(blank=True, db_column='K', max_length=255)),
                ('l', models.CharField(blank=True, db_column='L', max_length=255)),
                ('m', models.CharField(blank=True, db_column='M', max_length=255)),
                ('n', models.CharField(blank=True, db_column='N', max_length=255)),
                ('o', models.CharField(blank=True, db_column='O', max_length=255)),
                ('p', models.CharField(blank=True, db_column='P', max_length=255)),
                ('q', models.CharField(blank=True, db_column='Q', max_length=255)),
                ('r', models.CharField(blank=True, db_column='R', max_length=255)),
                ('s', models.CharField(blank=True, db_column='S', max_length=255)),
                ('t', models.CharField(blank=True, db_column='T', max_length=255)),
                ('answer', models.CharField(blank=True, db_column='ANSWER', max_length=255)),
                ('complexity', models.CharField(db_column='Complexity', max_length=255)),
                ('length', models.CharField(db_column='Length', max_length=255)),
            ],
            options={
                'db_table': 'core_question_orm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AbacusExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('length_of_question', models.PositiveIntegerField()),
                ('number_of_questions', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField(help_text='Speed in seconds or as per requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=32, unique=True)),
                ('teacher_identifier', models.CharField(max_length=100)),
                ('student_identifier', models.CharField(blank=True, max_length=100)),
                ('concept', models.CharField(max_length=100)),
                ('length_of_question', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField(help_text='Speed in seconds or as per requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_index', models.PositiveIntegerField(default=0, help_text='0-based pointer to current question in session')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(help_text='Serial number of the question', unique=True)),
                ('a', models.CharField(blank=True, help_text='Column A', max_length=50, null=True)),
                ('b', models.CharField(blank=True, help_text='Column B', max_length=50, null=True)),
                ('c', models.CharField(blank=True, help_text='Column C', max_length=50, null=True)),
                ('d', models.CharField(blank=True, help_text='Column D', max_length=50, null=True)),
                ('e', models.CharField(blank=True, help_text='Column E', max_length=50, null=True)),
                ('f', models.CharField(blank=True, help_text='Column F', max_length=50, null=True)),
                ('g', models.CharField(blank=True, help_text='Column G', max_length=50, null=True)),
                ('h', models.CharField(blank=True, help_text='Column H', max_length=50, null=True)),
                ('i', models.CharField(blank=True, help_text='Column I', max_length=50, null=True)),
                ('j', models.CharField(blank=True, help_text='Column J', max_length=50, null=True)),
                ('k', models.CharField(blank=True, help_text='Column K', max_length=50, null=True)),
                ('l', models.CharField(blank=True, help_text='Column L', max_length=50, null=True)),
                ('m', models.CharField(blank=True, help_text='Column M', max_length=50, null=True)),
                ('n', models.CharField(blank=True, help_text='Column N', max_length=50, null=True)),
                ('o', models.CharField(blank=True, help_text='Column O', max_length=50, null=True)),
                ('p', models.CharField(blank=True, help_text='Column P', max_length=50, null=True)),
                ('q', models.CharField(blank=True, help_text='Column Q', max_length=50, null=True)),
                ('r', models.CharField(blank=True, help_text='Column R', max_length=50, null=True)),
                ('s', models.CharField(blank=True, help_text='Column S', max_length=50, null=True)),
                ('t', models.CharField(blank=True, help_text='Column T', max_length=50, null=True)),
                ('answer', models.CharField(help_text='Correct answer', max_length=100)),
                ('complexity', models.CharField(blank=True, help_text='Question complexity/difficulty', max_length=50, null=True)),
                ('length', models.IntegerField(blank=True, help_text='Length of question', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_question',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('class_section', models.CharField(blank=True, max_length=20, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_id', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_user',
            },
        ),
        migrations.CreateModel(
            name='AssignedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=32)),
                ('legacy_serial', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(help_text='0-based order in session')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'unique_together': {('session_code', 'order_index')},
            },
        ),
    ]
