# Generated by Django 4.2.23 on 2025-08-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('length_of_question', models.PositiveIntegerField(help_text='Length of question (e.g., digits or terms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='abacusexercise',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='core.question'),
        ),
    ]
