# Generated by Django 4.2.23 on 2025-08-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livesession_assignedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyQuestion',
            fields=[
                ('serial', models.CharField(db_column='Serial', max_length=255, primary_key=True, serialize=False)),
                ('a', models.CharField(blank=True, db_column='A', max_length=255)),
                ('b', models.CharField(blank=True, db_column='B', max_length=255)),
                ('c', models.CharField(blank=True, db_column='C', max_length=255)),
                ('d', models.CharField(blank=True, db_column='D', max_length=255)),
                ('e', models.CharField(blank=True, db_column='E', max_length=255)),
                ('f', models.CharField(blank=True, db_column='F', max_length=255)),
                ('g', models.CharField(blank=True, db_column='G', max_length=255)),
                ('h', models.CharField(blank=True, db_column='H', max_length=255)),
                ('i', models.CharField(blank=True, db_column='I', max_length=255)),
                ('j', models.CharField(blank=True, db_column='J', max_length=255)),
                ('k', models.CharField(blank=True, db_column='K', max_length=255)),
                ('l', models.CharField(blank=True, db_column='L', max_length=255)),
                ('m', models.CharField(blank=True, db_column='M', max_length=255)),
                ('n', models.CharField(blank=True, db_column='N', max_length=255)),
                ('o', models.CharField(blank=True, db_column='O', max_length=255)),
                ('p', models.CharField(blank=True, db_column='P', max_length=255)),
                ('q', models.CharField(blank=True, db_column='Q', max_length=255)),
                ('r', models.CharField(blank=True, db_column='R', max_length=255)),
                ('s', models.CharField(blank=True, db_column='S', max_length=255)),
                ('t', models.CharField(blank=True, db_column='T', max_length=255)),
                ('answer', models.CharField(blank=True, db_column='ANSWER', max_length=255)),
                ('complexity', models.CharField(db_column='Complexity', max_length=255)),
                ('length', models.CharField(db_column='Length', max_length=255)),
            ],
            options={
                'db_table': 'core_question',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='legacy_serial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assignedquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.question'),
        ),
        migrations.AlterModelTable(
            name='question',
            table='core_question_orm',
        ),
    ]
